version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./companies.csv:/app/companies.csv
      - ./locations.csv:/app/locations.csv

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
